#!/bin/sh
### BEGIN INIT INFO
# Provides:          LEDwatchdog
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop LEDwatchdog.
# Description:       This script starts/stops LEDwatchdog.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh


res=0

case "$1" in
  start)

	## run watchdog
	sudo python /home/pi/makerpass/MakerPass/LEDwatchdog.py > /dev/null 2>&1 &

	;;
  restart|reload|force-reload)

	#kill all associated processes
	sudo python /home/pi/makerpass/install/KillAllLEDwatchdogProcesses.py

	## run watchdog
	sudo python /home/pi/makerpass/MakerPass/LEDwatchdog.py  > /dev/null 2>&1 &
	
	;;
  stop)
	#kill all associated processes
	sudo python /home/pi/makerpass/install/KillAllLEDwatchdogProcesses.py
	;;
  status)
	
	;;
  *)
	echo "Usage: LEDwatchdog [start|stop|status]" >&2
	res=3
	;;
esac

exit $res
