#!/bin/sh
### BEGIN INIT INFO
# Provides:          makerpass
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop makerpass.
# Description:       This script starts/stops makerpass.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh


res=0

case "$1" in
  start)
	## run makerpass
	/home/pi/makerpass/MakerPass/run_makerpass.bash > /dev/null 2>&1 &

	;;
  restart|reload|force-reload)
	sudo killall python

	## run makerpass
	/home/pi/makerpass/MakerPass/run_makerpass.bash > /dev/null 2>&1 &
	
	;;
  stop)
	sudo killall python
	;;
  status)
	
	;;
  *)
	echo "Usage: makerpass [start|stop|status]" >&2
	res=3
	;;
esac

exit $res
